type ApplicantEmailTemplateInput = {
  title: string;
  subtitle: string;
  message: string;
  roleTitle?: string;
  actionText?: string;
  actionUrl?: string;
};

function resolveEmailAssetBaseUrl() {
  const configured = (
    process.env.EMAIL_ASSET_BASE_URL ||
    process.env.PUBLIC_BASE_URL ||
    "https://mindlift-backend.vercel.app"
  )
    .trim()
    .replace(/^['\"]|['\"]$/g, "")
    .replace(/\/+$/, "");

  return configured;
}

export function generateApplicantNotificationEmail({
  title,
  subtitle,
  message,
  roleTitle,
  actionText,
  actionUrl,
}: ApplicantEmailTemplateInput) {
  const logoUrl = `${resolveEmailAssetBaseUrl()}/public/MindLift-Logo.jpg`;

  const roleBlock = roleTitle
    ? `<p style="margin:10px 0 0;color:#64748b;line-height:1.7;"><strong style="color:#0f172a;">Position:</strong> ${roleTitle}</p>`
    : "";

  const actionBlock =
    actionText && actionUrl
      ? `<div style="margin-top:18px;"><a href="${actionUrl}" style="display:inline-block;border-radius:12px;padding:10px 14px;font-size:14px;font-weight:700;text-decoration:none;background:#2563eb;color:#ffffff;">${actionText}</a></div>`
      : "";

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>MindLift Notification</title>
</head>
<body style="margin:0;padding:0;background:#f8fafc;font-family:Inter,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#0f172a;">
  <div style="padding:24px;">
    <div style="max-width:560px;margin:0 auto;background:#ffffff;border:1px solid #e2e8f0;border-radius:16px;overflow:hidden;box-shadow:0 10px 28px rgba(15,23,42,0.08);">
      <div style="padding:18px 22px;border-bottom:1px solid #e2e8f0;background:linear-gradient(90deg,rgba(37,99,235,0.12),rgba(37,99,235,0));">
        <div style="display:flex;align-items:center;gap:10px;">
          <span style="display:inline-flex;align-items:center;justify-content:center;width:28px;height:28px;border-radius:9999px;background:#dbeafe;border:1px solid #bfdbfe;overflow:hidden;">
            <img src="${logoUrl}" alt="MindLift logo" width="18" height="18" style="display:block;object-fit:cover;border-radius:9999px;" />
          </span>
          <p style="margin:0;font-size:18px;font-weight:800;letter-spacing:-0.02em;color:#2563eb;">MindLift</p>
        </div>
      </div>
      <div style="padding:24px 22px;">
        <h1 style="margin:0 0 8px;font-size:24px;line-height:1.3;letter-spacing:-0.02em;">${title}</h1>
        <p style="margin:0 0 10px;color:#64748b;line-height:1.7;">${subtitle}</p>
        ${roleBlock}
        <div style="margin-top:14px;border:1px solid #e2e8f0;border-radius:14px;background:#f8fafc;padding:16px;">
          <p style="margin:0;color:#0f172a;line-height:1.75;white-space:pre-line;">${message}</p>
        </div>
        ${actionBlock}
      </div>
      <div style="padding:14px 22px;border-top:1px solid #e2e8f0;background:#f8fafc;color:#64748b;font-size:12px;line-height:1.6;">
        This email was automatically generated by MindLift. Please do not reply directly.
      </div>
    </div>
  </div>
</body>
</html>
`;
}
